SELECT SERVICE_ID,
         TRUNC (CREATION_DATE, 'HH24')        DATE_PER_HOUR,
         COUNT (*)                            COUNT_PER_HOUR,
         TRUNC (AVG (TOTAL_REQUEST_TIME))     AVERAGE_RESPONE_TIME
    FROM H_RECEIVED_REQUESTS
WHERE CREATION_DATE BETWEEN TRUNC(SYSDATE-1) AND TRUNC(SYSDATE)
GROUP BY SERVICE_ID, TRUNC (CREATION_DATE, 'HH24');